repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'npm run lint && npm run type-check'
        language: system
        files: ^src/
        types: [file]
